### PR TITLE
Accessing current width and current breakpoint name

### PR DESCRIPTION
**Pull request by Entkenntnis**
Sometimes it's useful to access context variables directly, e.g. if you want to write your own logic (in conjunction with react-socks).

Implementing it with react hooks is quite straight forward, here is a PR.

### CODE REVIEW

**Comment by pgegenfurtner** [comment]
@flexdinesh When will you merge this? Need this feature 😊

**Comment by flexdinesh** [comment]
@pgegenfurtner I haven't gotten to this yet. But I will definitely get this done this week. Should be available from npm next week I promise :)

Gotta run a few tests against hooks and see how it's fairing and will release it as a new version.

**Comment by flexdinesh** [comment]
This is a breaking change. Will have to upgrade peer dependency to a React version that supports hooks and should do a major version bump. I'll get this done this week.

**Comment by flexdinesh** [comment]
Changes released with `v2.0.0`. Thank you!

**Pull request merged**
